config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => {:registrations => "users/registrations"}
	resources :departments 
	resources :teams 
	resources :users do
  		resources :requests
  		get "managed_requests" => 'requests#managed_requests', as: :managed_requests
	end		  	
	root "home#dashboard"
  	get 'hello_world', to: 'hello_world#index'
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable

	
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
	enum role: [:admin, :dept_head, :manager, :employee]
	has_many :requests, dependent: :destroy
	belongs_to :team

  	ADMINS = User.admin
    DEPT_HEADS = User.admin | User.dept_head
    EMPLOYEE = User.employee

	def full_name 
		"#{first_name} " + "#{last_name}"
	end

	def managed_users
		managed_users = []
		case role
			when "admin"
				managed_users << User.all
			when "dept_head"
				departments = Department.where(dept_head_id: self.id)
				departments.each do |department|
					department.users.each do |user|	
						managed_users << user
					end	
				end	
				teams = Team.where(manager_id: self.id)
				teams.each do |team|
					team.users.each do |user|	
						managed_users << user
					end	
				end			
			when "manager"
				teams = Team.where(manager_id: self.id)
				teams.each do |team|
					team.users.each do |user|	
						managed_users << user
					end	
				end
		end
		if managed_users.include? self
			return managed_users.uniq.delete(self)
		else
			return managed_users.uniq
		end
	end

	def managed_teams
		managed_teams = []
		if dept_head?
			departments = Department.joins(:teams).where("manager_id = ?", id).uniq
			departments.each do |department|
				department.teams.each do |team|	
					managed_teams << team
				end	
			end
		else
			unless employee?
				managed_teams = Team.where(manager_id: self.id)
			end
		end	
		return managed_teams
	end

	def total_approved_pto
	end

	def total_pending_pto
	end

	def total_declined_pto
	end		

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    binding.pry
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_is_admin, except: [:show, :edit, :update]
  helper_method :sort_column, :sort_direction

  def index
    @users = User.order(sort_column + ' ' + sort_direction)
  end

  def show
    sort_method_name = sort_requests_column
    @all_requests = @user.requests.sort_by { |request| request.public_send(sort_method_name) }
    @approved_requests = @user.requests.select(&:approved?)
    @pending_requests = @user.requests.select(&:pending?)
    @declined_requests  = @user.requests.select(&:declined?)
    if sort_direction == "desc"
      @all_requests = @all_requests.reverse!
    end
  end

  def new
    @user = User.new
    @teams = Team.all
  end

  def edit
    @teams = Team.all
  end

  def create
    @teams = Team.all
    @user = User.new(user_params)
    if user_params[:team_id]
      @user.team_name = (Team.find user_params[:team_id]).team_name
    end
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @teams = Team.all
    respond_to do |format|
      unless user_params[:team_id].blank?
        @user.team_name = (Team.find user_params[:team_id]).team_name
      end
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
  def authenticate_is_admin
    current_user.admin?
  end 

  def sort_column
    params[:sort] || "last_name"
  end
  
  def sort_direction
    params[:direction] || "asc"
  end

  def sort_requests_column
    params[:sort] || "start_date"
  end

  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :role, :position, :team_name, :team_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <%- if current_user.admin? %>
    <div class="field">
      <%= f.label :role %>
      <%= f.select(:role, User.roles.keys.map { |role| [ role.titleize, role ] }, :selected => user.role) %>
    </div>
  <%- end %>  

  <div class="field">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>

  <div class="field">
    <%= f.label :team_name, "Team" %>
    <%= f.select(:team_id, @teams.map { |team| [ team.team_name, team.id ] }, :include_blank => true) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="1"></th>

      <th>
          <%= sortable "First Name" %>
      </th>
      <th>
          <%= sortable "Last Name" %>
      </th>
      <th>
          <%= sortable "Role" %>
      </th>
      <th>
          <%= sortable "Position" %>
      </th>
      <th>
          <%= sortable "Team Name" %>
      </th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each_with_index do |user, i| %>
      <tr>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.role.titleize %></td>
        <td><%= user.position %></td>
        <%- if user.team %>  
          <td><%= user.team.team_name %></td>
        <%- else %>  
          <td>Not Yet Assigned to a Team</td>
        <%- end %>  
          
        <td><%= link_to 'User Details', user %></td>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

<!-- User.all.each { |u| u.update_attributes({team_id: 17}) if u.team_name == "Team Lion" && u.team_id.blank? }
 -->

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role.titleize %>
</p>

<p>
  <strong>Position:</strong>
  <%= @user.position %>
</p>

<p>
  <strong>Team name:</strong>
  <%= @user.team_name %>
</p>

<%- if @all_requests.empty? %>
  <p><%= "#{@user.full_name} "%> has no PTO requests.</p>
<% else %>
  <table>
    <thead>
    <h4>
      All Requests
    </h4>
    <p>
      Total Requests: <%= @all_requests.count || "0" %> 
    </p>
    <p>
      Total Pending Requests: <%= @pending_requests.count || "0" %> 
    </p>    
    <p>
      Total Aprroved Requests: <%= @approved_requests.count || "0" %> 
    </p>    
    <p>
      Total Declined Requests: <%= @declined_requests.count || "0" %> 
    </p>
      <tr>
        <th>
            <%= sortable "Status" %>
        </th>
        <th>
            <%= sortable "Start Date" %>
        </th>
        <th>
            <%= sortable "End Date" %>
        </th>
        <th>
            <%= sortable "Note" %>
        </th>
      </tr>
    </thead>

    <tbody>
      <% @all_requests.each_with_index do |request, i| %>
        <tr>
          <td><%= request.status.titleize %></td>
          <td><%= request.start_date.strftime("%m/%d/%Y") %></td>
          <td><%= request.end_date.strftime("%m/%d/%Y") %></td>
          <td><%= request.note %></td>          
          <td><%= link_to 'Edit Request', edit_user_request_path(@user, request ) %></td>
          <td><%= link_to 'Delete Request', user_request_path(@user, request), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end-%>


<%- if current_user.admin? %>
	<%= link_to 'Edit', edit_user_path(@user) %> |
<% end -%>
<%- unless current_user.employee? %>
	<%= link_to 'Back to all Users', users_path %>
<% end -%>	