config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => {:registrations => "users/registrations"}
	resources :departments 
	resources :teams 
	resources :users do
  		resources :requests
  		get "managed_requests" => 'requests#managed_requests', as: :managed_requests
	end		  	
	root "home#dashboard"
  	get 'hello_world', to: 'hello_world#index'
end

app/models/department.rb
class Department < ApplicationRecord
	has_many :teams
	has_many :users, through: :teams
	
	def department_head
		User.find dept_head_id
	end

	def teams
		teams = Team.where department_id: id
	end
	
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]


  def index
    @departments = Department.all
  end

  def show
    @teams = Team.where( department_id: @department.id )
  end

  def new
    @department = Department.new
    @department_heads = User.admin | User.dept_head
  end

  def edit
    @department_heads = User.admin | User.dept_head
  end

  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:department_name, :dept_head_id)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_for(department) do |f| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :department_name, "Department Name" %>
    <%= f.text_field :department_name %>
  </div>

  <div class="field">
    <%= f.label :dept_head_id, "Department Head" %>
    <%= f.select(:dept_head_id, @department_heads.map { |dept_head| [ dept_head.full_name, dept_head.id ] }) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dept Head</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.department_name %></td>
        <td><%= User.find(department.dept_head_id).full_name %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form', department: @department, department_heads: @department_heads %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Department name:</strong>
  <%= @department.department_name %>
</p>

<p>
  <strong>Dept head:</strong>
  <%= User.find(@department.dept_head_id).full_name %>
</p>

<% if !@teams.blank? %>
<h3>
	Teams in <%= @department.department_name %> department:
</h3>
	<% for team in @teams %>
		<%= link_to "#{team.team_name}", team_path(team) %><br>
	<% end %>
<% else %>
	
<% end %>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>