config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => {:registrations => "users/registrations"}
	resources :departments 
	resources :teams 
	resources :users do
  		resources :requests
  		get "managed_requests" => 'requests#managed_requests', as: :managed_requests
	end		  	
	root "home#dashboard"
  	get 'hello_world', to: 'hello_world#index'
end

app/models/request.rb
class Request < ApplicationRecord
	enum status: [:pending, :approved, :declined]
	belongs_to :user
	validates :start_date, presence: true, date: { before_or_equal_to: :end_date, message: " of a request must be before its end."} 
	validates_presence_of :end_date
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.find params[:user_id]
    @requests = @user.requests
  end

  def show
    @user = User.find params[:user_id]
  end

  def new
    @request = Request.new
    @user = User.find params[:user_id]
  end

  def edit
    @user = User.find params[:user_id]
  end

  def create
    @request = Request.new(request_attrs(request_params))
    @user = User.find params[:user_id]
    @request.user = @user
    respond_to do |format|
      if @request.save
        format.html { redirect_to user_request_path(@user, @request), notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end 
  end

  def update
    @user = User.find params[:user_id]
    respond_to do |format|
      if @request.update(request_attrs(request_params))
        format.html { redirect_to user_request_path(@user, @request), notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @request.destroy
    @user = User.find params[:user_id]
    respond_to do |format|
      format.html { redirect_to user_requests_url(@user), notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def managed_requests
    @managed_users = current_user.managed_users.flatten
  end

  private
    
    def request_attrs(request_params)
      request_attrs = request_params.clone
      if !request_attrs["start_date"].blank?
        request_attrs["start_date"] = Date.strptime(request_attrs["start_date"], "%m/%d/%Y")
      end

      if !request_attrs["end_date"].blank?
        request_attrs["end_date"] = Date.strptime(request_attrs["end_date"], "%m/%d/%Y")
      end
      return request_attrs
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:start_date, :end_date, :status, :note, :user_id)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for [@user, request] do |f| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.text_field :start_date, class: "datepicker", value: request.start_date && request.start_date.strftime("%m/%d/%Y") || "" %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.text_field :end_date, class: "datepicker", value: request.end_date && request.end_date.strftime("%m/%d/%Y") || "" %>
  </div>

  <%- unless current_user.employee? %>
    <div class="field">
      <%= f.label :status %>
      <%= f.select(:status, Request.statuses.keys.map { |status| [ status.titleize, status ] }, :selected => request.status) %>
    </div>
  <%- end %>


  <div class="field">
    <%= f.label :note %>
    <%= f.text_area :note %>
  </div>

  <%= hidden_field(:user_id, @user.id) %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back to User Details', user_path(@user) %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Status</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.start_date.strftime("%m/%d/%Y") %></td>
        <td><%= request.end_date.strftime("%m/%d/%Y") %></td>
        <td><%= request.status %></td>
        <td><%= request.note %></td>
        <td><%= link_to 'Show', user_request_path(@user, request) %></td>
        <td><%= link_to 'Edit', edit_user_request_path(@user, request) %></td>
        <td><%= link_to 'Destroy', user_request_path(@user, request), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_user_request_path(@user) %>

app/views/requests/managed_requests.html.erb
<% if !@managed_users.blank? %>
	<table>
		<thead>
			<tr>
				<th>User Name</th>
				<th>Start Date</th>
				<th>End Date</th>
				<th>Status</th>
				<th>Note</th>
				<th colspan="3"></th>
			</tr>
		</thead>
	  	<tbody>
	<% for user in @managed_users %>
	    <%- unless user.requests.blank? %>
			<%- for request in user.requests %>

		      <tr>
		        <td><%= user.full_name %></td>
		        <td><%= request.start_date %></td>
		        <td><%= request.end_date %></td>
		        <td><%= request.status %></td>
		        <td><%= request.note %></td>
		        <td><%= link_to 'Show', user_request_path(user, request) %></td>
		        <td><%= link_to 'Edit', edit_user_request_path(user, request) %></td>
		        <td><%= link_to 'Destroy', user_request_path(user, request), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		      </tr>
	    	<%- end %>
	    <%- end %>	
	<% end %>
		</tbody>
	</table>
<% end %>
	

app/views/requests/new.html.erb
<h1>New Request</h1>

<div id="flash_messages">
	<%- if flash[:date_error] %>
		<p class="error">
			<%= flash[:date_error] %>
		</p>
	<%end -%>
</div>

<%= render 'form', request: @request %>

<%= link_to 'Back', user_requests_path(@user) %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Start date:</strong>
  <%= @request.start_date.strftime("%m/%d/%Y") %>
</p>

<p>
  <strong>End date:</strong>
  <%= @request.end_date.strftime("%m/%d/%Y") %>
</p>

<p>
  <strong>Status:</strong>
  <%= @request.status %>
</p>

<p>
  <strong>Note:</strong>
  <%= @request.note %>
</p>

<%= link_to 'Edit', edit_user_request_path(@user, @request) %> |
<%= link_to 'Back', user_requests_path(@user) %>